In [ ]:
import numpy as np

arr = np.random.randint(1,21,size=(5,5))
arr

arr[:][3] = 1;
arr

In [15]:
import numpy as np

# Create 4x4 array with values 1 to 16
arr = np.arange(1, 17).reshape(4, 4)

# Replace diagonal elements with 0
np.fill_diagonal(arr, 0)

print(arr)


[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [23]:
import numpy as np

# Create a 6x6 array with values from 1 to 36
arr = np.arange(1, 37).reshape(6, 6)

# Extract sub-array: rows 3–5 and columns 2–4 (indexing starts from 0)
sub_arr = arr[2:5, 1:4]

print("Original Array:\n", arr)
print("\nExtracted Sub-array:\n", sub_arr)


Original Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Extracted Sub-array:
 [[14 15 16]
 [20 21 22]
 [26 27 28]]


In [28]:
arr = np.random.randint(0,100,size=(5,5))
print(arr)
sub_arr = arr[1:3, 1:3]
sub_arr

array([[44, 62],
       [36, 77]], dtype=int32)