In [2]:
!pip install numpy

In [11]:
# NumPy = Best for numerical and matrix operations.

# Pandas = Best for analyzing and manipulating structured data (like tables).
import numpy as np

In [4]:
#create arrays using numpy
arr1 = np.array([1,2,3,4,5])

In [5]:
print(arr1)

[1 2 3 4 5]


In [6]:
print(type(arr1))

<class 'numpy.ndarray'>


In [7]:
print(arr1.shape)

(5,)


In [8]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)#1 row 5 columns

array([[1, 2, 3, 4, 5]])

In [9]:
arr2.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
arr2.ndim

1

In [17]:
arr2.dtype

dtype('int64')

In [18]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,11,12,13,0])

print(arr1 + arr2)

[11 13 15 17  5]


In [19]:
print(arr1 - arr2)

[-9 -9 -9 -9  5]


In [20]:
print(arr1 * arr2)

[10 22 36 52  0]


In [21]:
print(arr1 / arr2)

[0.1        0.18181818 0.25       0.30769231        inf]


C:\Users\smrut\AppData\Local\Temp\ipykernel_5572\933723721.py:1: RuntimeWarning: divide by zero encountered in divide
  print(arr1 / arr2)


In [23]:
arr = np.array([1,2,3,4,5,6])

print(np.sqrt(arr))
print("--")
print(np.exp(arr))
print("--")
print(np.sin(arr))
print("--")
print(np.log(arr))




[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
--
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
--
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
--
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [24]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
arr[0]

array([1, 2, 3, 4])

In [26]:
arr[0][0]

np.int64(1)

In [28]:
arr[1:][2:]

array([], shape=(0, 4), dtype=int64)

In [29]:
print(arr[0, 0])
print(arr[1:, 2:])
print(arr[1:, :2])
print(arr[1:, 1:3])


1
[[ 7  8]
 [11 12]]
[[ 5  6]
 [ 9 10]]
[[ 6  7]
 [10 11]]


In [30]:
arr[0,0]= 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [31]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [32]:
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
std = np.std(data)
normalized_data = (data - mean) / std
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [36]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("MEAN",np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

MEAN 5.5
5.5
2.8722813232690143
8.25


In [34]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(data > 5)
print(data[data > 5])
print(data[(data >= 5) & (data <= 8)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[5 6 7 8]
